# Generated by Django 4.0.3 on 2022-04-03 18:35

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='活动名称 --string', max_length=100, verbose_name='活动名称')),
                ('begin_time', models.DateTimeField(help_text='开始时间', verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('contain', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='人数限制')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='活动描述')),
                ('review', models.BooleanField(default=False, verbose_name='是否需要审核')),
                ('avatar', models.CharField(blank=True, max_length=500, null=True, verbose_name='活动图片')),
                ('keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='关键词')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='地址名称')),
                ('longitude', models.DecimalField(decimal_places=25, max_digits=30, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=25, max_digits=30, verbose_name='纬度')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='版块名称')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='操作内容')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(8, '被设置为管理员通知'), (9, '被移出管理员通知'), (2, '参与的活动被取消通知'), (6, '创建组织请求审批结果'), (7, '被转让为负责人通知'), (5, '管理的活动被评价的通知'), (4, '新博雅通知'), (1, '参与的活动的内容变更通知'), (10, '管理的活动评论被修改的通知'), (3, '被移除出活动通知')], verbose_name='通知类型')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('content', models.CharField(max_length=500, verbose_name='通知内容')),
                ('act', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BUAA.activity', verbose_name='活动')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='组织名称')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='组织描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('avatar', models.CharField(blank=True, max_length=500, null=True, verbose_name='头像')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.block', verbose_name='所属版块')),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.CharField(blank=True, max_length=500, null=True, verbose_name='头像')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WXUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(help_text='微信openid --string', max_length=500, unique=True, verbose_name='微信openid')),
                ('name', models.CharField(help_text='昵称 --string', max_length=30, verbose_name='昵称')),
                ('avatar', models.CharField(blank=True, help_text='头像 --string', max_length=500, null=True, verbose_name='头像')),
                ('email', models.EmailField(help_text='邮箱 --string', max_length=100, null=True, verbose_name='邮箱')),
                ('sign', models.CharField(blank=True, help_text='个性签名 --string', max_length=200, null=True, verbose_name='个性签名')),
                ('contact', models.CharField(blank=True, help_text='联系方式 --string', max_length=50, null=True, verbose_name='联系方式')),
                ('follow_boya', models.BooleanField(default=False, verbose_name='是否关注博雅版块')),
                ('user_portrait', models.CharField(blank=True, max_length=200, null=True, verbose_name='用户画像路径')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='反馈内容')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.wxuser', verbose_name='用户名')),
            ],
        ),
        migrations.CreateModel(
            name='SentNotif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('already_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('notif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.notification', verbose_name='通知')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.wxuser', verbose_name='接收人员')),
            ],
        ),
        migrations.CreateModel(
            name='OrgManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.organization', verbose_name='组织')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.wxuser', verbose_name='组织管理员')),
            ],
        ),
        migrations.CreateModel(
            name='OrgApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='组织名称')),
                ('description', models.CharField(max_length=500, verbose_name='申请描述')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('status', models.SmallIntegerField(choices=[(0, '待审批'), (1, '审批通过'), (2, '审批未通过')], default=0, verbose_name='审批状态')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.block', verbose_name='所属版块')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.wxuser', verbose_name='申请人')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.wxuser', verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='notification',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BUAA.organization', verbose_name='组织'),
        ),
        migrations.CreateModel(
            name='ManagerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=500, null=True, verbose_name='理由')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.organization', verbose_name='组织')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.wxuser', verbose_name='申请用户')),
            ],
        ),
        migrations.CreateModel(
            name='JoinedAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.activity', verbose_name='活动')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.wxuser', verbose_name='报名人员')),
            ],
        ),
        migrations.CreateModel(
            name='JoinActApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.activity', verbose_name='申请活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.wxuser', verbose_name='申请人')),
            ],
        ),
        migrations.CreateModel(
            name='FollowedOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.organization', verbose_name='关注的组织')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.wxuser', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, null=True, verbose_name='内容')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('score', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='评分')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.activity', verbose_name='所属活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.wxuser', verbose_name='所属用户')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.block', verbose_name='所属版块'),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.address', verbose_name='活动地点'),
        ),
        migrations.AddField(
            model_name='activity',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BUAA.organization', verbose_name='所属组织'),
        ),
        migrations.AddField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.wxuser', verbose_name='发起者'),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BUAA.category', verbose_name='分类'),
        ),
    ]
