# Generated by Django 4.0.3 on 2022-04-15 16:41

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BUAA', '0005_alter_superadmin_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='superadmin',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='groundapply',
            old_name='can_change',
            new_name='if_change',
        ),
        migrations.RenameField(
            model_name='userverify',
            old_name='student_number',
            new_name='student_id',
        ),
        migrations.RemoveField(
            model_name='groundapply',
            name='apply_group',
        ),
        migrations.RemoveField(
            model_name='groundapply',
            name='begin_time',
        ),
        migrations.RemoveField(
            model_name='groundapply',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='groundapply',
            name='file',
        ),
        migrations.RemoveField(
            model_name='groundapply',
            name='identity',
        ),
        migrations.AddField(
            model_name='groundapply',
            name='period',
            field=models.SmallIntegerField(choices=[(0, 'xxx'), (1, 'xxx'), (2, 'xxx')], default=0, verbose_name='申请时间段'),
        ),
        migrations.AddField(
            model_name='groundapply',
            name='time',
            field=models.DateTimeField(default='2001-01-01 00:00:00', verbose_name='申请时间'),
        ),
        migrations.AlterField(
            model_name='groundapply',
            name='ground_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.ground', verbose_name='预约的场地id'),
        ),
        migrations.AlterField(
            model_name='groundapply',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '申请中'), (1, '已通过'), (2, '未通过')], default=0, verbose_name='申请状态'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.SmallIntegerField(choices=[(8, '被设置为管理员通知'), (9, '被移出管理员通知'), (1, '参与的活动的内容变更通知'), (6, '创建组织请求审批结果'), (2, '参与的活动被取消通知'), (3, '被移除出活动通知'), (4, '新博雅通知'), (5, '管理的活动被评价的通知'), (10, '管理的活动评论被修改的通知'), (7, '被转让为负责人通知')], verbose_name='通知类型'),
        ),
    ]
