# Generated by Django 4.0.3 on 2022-04-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BUAA', '0006_alter_superadmin_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='superadmin',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='groundapply',
            old_name='if_change',
            new_name='can_change',
        ),
        migrations.RenameField(
            model_name='userverify',
            old_name='student_id',
            new_name='student_number',
        ),
        migrations.RemoveField(
            model_name='groundapply',
            name='period',
        ),
        migrations.RemoveField(
            model_name='groundapply',
            name='time',
        ),
        migrations.AddField(
            model_name='groundapply',
            name='apply_group',
            field=models.SmallIntegerField(default=0, verbose_name='预约组号'),
        ),
        migrations.AddField(
            model_name='groundapply',
            name='begin_time',
            field=models.DateTimeField(default='2001-01-01 00:00:00', verbose_name='申请开始时间'),
        ),
        migrations.AddField(
            model_name='groundapply',
            name='end_time',
            field=models.DateTimeField(default='2001-01-01 00:00:00', verbose_name='申请结束时间'),
        ),
        migrations.AddField(
            model_name='groundapply',
            name='file',
            field=models.CharField(max_length=500, null=True, verbose_name='申请材料'),
        ),
        migrations.AddField(
            model_name='groundapply',
            name='identity',
            field=models.SmallIntegerField(choices=[(0, '普通用户'), (1, '组织者')], default=0, verbose_name='申请者身份'),
        ),
        migrations.AlterField(
            model_name='groundapply',
            name='ground_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUAA.ground', verbose_name='申请场地id'),
        ),
        migrations.AlterField(
            model_name='groundapply',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '已通过'), (1, '审核中'), (2, '已失效')], default=0, verbose_name='申请状态'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.SmallIntegerField(choices=[(6, '创建组织请求审批结果'), (4, '新博雅通知'), (10, '管理的活动评论被修改的通知'), (2, '参与的活动被取消通知'), (7, '被转让为负责人通知'), (8, '被设置为管理员通知'), (5, '管理的活动被评价的通知'), (1, '参与的活动的内容变更通知'), (3, '被移除出活动通知'), (9, '被移出管理员通知')], verbose_name='通知类型'),
        ),
    ]
