# Generated by Django 4.0.3 on 2022-04-23 17:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BUAA', '0013_ground_begin_time_ground_end_time_wxuser_real_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='administrator',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='BUAA.superadmin', verbose_name='场地管理员'),
        ),
        migrations.AlterField(
            model_name='groundapply',
            name='apply_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 17, 51, 46, 655978), verbose_name='申请提交的时间，同批次都相同'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.SmallIntegerField(choices=[(7, '被转让为负责人通知'), (1, '参与的活动的内容变更通知'), (3, '被移除出活动通知'), (10, '管理的活动评论被修改的通知'), (4, '新博雅通知'), (2, '参与的活动被取消通知'), (6, '创建组织请求审批结果'), (8, '被设置为管理员通知'), (9, '被移出管理员通知'), (5, '管理的活动被评价的通知')], verbose_name='通知类型'),
        ),
    ]
