# Generated by Django 3.2.13 on 2022-05-01 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUAA', '0025_alter_groundapply_apply_time_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundapply',
            name='apply_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 19, 8, 46, 111818), verbose_name='申请提交的时间，同批次都相同'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.SmallIntegerField(choices=[(6, '创建组织请求审批结果'), (9, '被移出管理员通知'), (2, '参与的活动被取消通知'), (4, '新博雅通知'), (10, '管理的活动评论被修改的通知'), (3, '被移除出活动通知'), (8, '被设置为管理员通知'), (1, '参与的活动的内容变更通知'), (7, '被转让为负责人通知'), (5, '管理的活动被评价的通知')], verbose_name='通知类型'),
        ),
    ]
