# Generated by Django 3.2.13 on 2022-05-05 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUAA', '0048_auto_20220504_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundapply',
            name='apply_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 19, 32, 0, 771534), verbose_name='申请提交的时间，同批次都相同'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.SmallIntegerField(choices=[(3, '被移除出活动通知'), (6, '创建组织请求审批结果'), (7, '被转让为负责人通知'), (5, '管理的活动被评价的通知'), (9, '被移出管理员通知'), (10, '管理的活动评论被修改的通知'), (4, '新博雅通知'), (2, '参与的活动被取消通知'), (1, '参与的活动的内容变更通知'), (8, '被设置为管理员通知')], verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='openid',
            field=models.CharField(help_text='微信openid --string', max_length=200, unique=True, verbose_name='微信openid'),
        ),
    ]
